format_version: 3
pipelines:
  sonar-scanner-demo-2:
    group: xiaoqu
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/1483523635/money-tracker 
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - scan:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          scan:
            timeout: 0
            tasks:
            - exec:
                command: sonar-scanner
                run_if: passed
