format_version: 3
pipelines:
  sonar-as-code:
    group: default
    materials:
      git:
        git: https://github.com/1483523635/money-tracker
        auto_update: true
        branch: master
    stages:
    - analyize:
        fetch_materials: true
        clean_workspace: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          sonar-scanner:
            timeout: 0
            tasks:
            - exec:
                command: pwd
                run_if: passed
            - exec:
                command: sonar-scanner
                run_if: passed
            - plugin:
                configuration:
                  id: script-executor
                  version: 0.3.0
                options:
                  script: |-
                    . "/Users/lqqu/.zshrc"
                    sonar-scanner
                  shtype: bash
                run_if: passed

